"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import type { User } from "@supabase/supabase-js";
import { getApiUrl } from "@/lib/api";

export interface UserProfile {
  user_id: string;
  display_name: string;
  created_at: string;
  updated_at: string;
  isFallback?: boolean;
  isAutoGenerated?: boolean;
  isCustom?: boolean;
}

const PROFILE_STORAGE_KEY_PREFIX = "mezship_profile_";
const LAST_USER_ID_KEY = "mezship_last_user_id";
const CUSTOM_NAME_KEY_PREFIX = "mezship_custom_name_";

function getCachedProfile(userId?: string): UserProfile | null {
  if (typeof window === "undefined") return null;
  try {
    const id = userId || localStorage.getItem(LAST_USER_ID_KEY);
    if (!id) return null;
    const raw = localStorage.getItem(`${PROFILE_STORAGE_KEY_PREFIX}${id}`);
    if (raw) {
      const parsed = JSON.parse(raw) as UserProfile;
      const customName = localStorage.getItem(`${CUSTOM_NAME_KEY_PREFIX}${id}`);
      if (customName) {
        parsed.display_name = customName;
        parsed.isCustom = true;
      }
      return parsed;
    }
  } catch (e) {
    console.warn("Failed to read cached profile:", e);
  }
  return null;
}

function setCachedProfile(userId: string, profile: UserProfile) {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(LAST_USER_ID_KEY, userId);
    localStorage.setItem(`${PROFILE_STORAGE_KEY_PREFIX}${userId}`, JSON.stringify(profile));
  } catch (e) {
    console.warn("Failed to set cached profile:", e);
  }
}

function clearCachedProfile(userId?: string) {
  if (typeof window === "undefined") return;
  try {
    if (userId) {
      localStorage.removeItem(`${PROFILE_STORAGE_KEY_PREFIX}${userId}`);
      localStorage.removeItem(`${CUSTOM_NAME_KEY_PREFIX}${userId}`);
    }
    localStorage.removeItem(LAST_USER_ID_KEY);
  } catch (e) {
    console.warn("Failed to clear cached profile:", e);
  }
}

export function useAuth() {
  const [user, setUser] = useState<User | null>(null);
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [loading, setLoading] = useState(true);
  const [token, setToken] = useState<string | null>(null);
  const supabase = createClient();

  useEffect(() => {
    let isMounted = true;

    // Hydrate cached profile immediately on client mount without causing SSR hydration mismatch
    const initialCached = getCachedProfile();
    if (initialCached && isMounted) {
      setProfile(initialCached);
    }

    async function initAuth() {
      try {
        const { data, error: sessionErr } = await supabase.auth.getSession();
        if (!isMounted) return;

        if (data?.session) {
          let session = data.session;
          // Auto-refresh expired or nearly expired tokens
          const now = Math.floor(Date.now() / 1000);
          if (session.expires_at && session.expires_at < now + 60) {
            try {
              const { data: refreshData } = await supabase.auth.refreshSession();
              if (refreshData?.session) {
                session = refreshData.session;
              }
            } catch (refErr) {
              console.warn("Session refresh error:", refErr);
            }
          }

          if (!isMounted) return;
          setUser(session.user);
          setToken(session.access_token);

          const cached = getCachedProfile(session.user.id);
          if (cached) {
            setProfile(cached);
          }
          setLoading(false);

          await fetchProfile(session.access_token, session.user.id);
        } else {
          // If explicitly unauthenticated and no session error
          if (!sessionErr) {
            setUser(null);
            setProfile(null);
            setToken(null);
            clearCachedProfile();
          }
          if (isMounted) setLoading(false);
        }
      } catch (err) {
        console.error("Auth init error:", err);
        if (isMounted) setLoading(false);
      }
    }

    initAuth();

    const { data: authListener } = supabase.auth.onAuthStateChange(
      async (event, session) => {
        if (!isMounted) return;
        if (session) {
          setUser(session.user);
          setToken(session.access_token);

          const cached = getCachedProfile(session.user.id);
          if (cached) {
            setProfile(cached);
          }
          setLoading(false);

          await fetchProfile(session.access_token, session.user.id);
        } else if (event === "SIGNED_OUT") {
          setUser(null);
          setProfile(null);
          setToken(null);
          clearCachedProfile();
          setLoading(false);
        }
      }
    );

    return () => {
      isMounted = false;
      authListener.subscription.unsubscribe();
    };
  }, []);

  async function fetchProfile(accessToken: string, userId: string) {
    try {
      const res = await fetch(getApiUrl("/api/profile"), {
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      });

      const cached = getCachedProfile(userId);
      const customSavedName =
        typeof window !== "undefined"
          ? localStorage.getItem(`${CUSTOM_NAME_KEY_PREFIX}${userId}`)
          : null;
      const hasCustomName = Boolean(customSavedName || cached?.isCustom);

      if (res.ok) {
        const data = (await res.json()) as {
          profile: UserProfile;
          isFallback?: boolean;
          isAutoGenerated?: boolean;
        };
        if (data.profile) {
          const isAutoFallbackOrGenerated =
            data.isFallback ||
            data.isAutoGenerated ||
            data.profile.display_name.startsWith("Echo") ||
            data.profile.display_name.startsWith("User");

          // If the user picked a custom name, never overwrite it with an auto-generated pseudonym or DB fallback
          if (hasCustomName && isAutoFallbackOrGenerated) {
            const customName = customSavedName || cached?.display_name;
            if (customName) {
              const customProfile: UserProfile = {
                ...data.profile,
                display_name: customName,
                isCustom: true,
              };
              setProfile(customProfile);
              setCachedProfile(userId, customProfile);

              // Background re-sync to persist custom name to DB now that connection/token is available
              fetch(getApiUrl("/api/profile"), {
                method: "POST",
                headers: {
                  "Content-Type": "application/json",
                  Authorization: `Bearer ${accessToken}`,
                },
                body: JSON.stringify({ displayName: customName }),
              }).catch(() => {});
              return;
            }
          }

          const finalProfile: UserProfile = {
            ...data.profile,
            isCustom: hasCustomName && !isAutoFallbackOrGenerated,
          };
          setProfile(finalProfile);
          setCachedProfile(userId, finalProfile);
        }
      } else {
        if (cached) {
          setProfile(cached);
        } else {
          const customName = customSavedName || `User${userId.slice(0, 5)}`;
          const fallback: UserProfile = {
            user_id: userId,
            display_name: customName,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            isFallback: true,
            isCustom: Boolean(customSavedName),
          };
          setProfile(fallback);
          setCachedProfile(userId, fallback);
        }
      }
    } catch (e) {
      console.warn("fetchProfile network error:", e);
      const cached = getCachedProfile(userId);
      if (cached) {
        setProfile(cached);
      }
    }
  }

  async function updateDisplayName(newDisplayName: string) {
    const trimmed = newDisplayName.trim();
    if (!trimmed) return false;

    // Optimistically update local profile immediately so user's choice is never lost
    if (user) {
      if (typeof window !== "undefined") {
        localStorage.setItem(`${CUSTOM_NAME_KEY_PREFIX}${user.id}`, trimmed);
      }
      const optimisticProfile: UserProfile = {
        user_id: user.id,
        display_name: trimmed,
        created_at: profile?.created_at || new Date().toISOString(),
        updated_at: new Date().toISOString(),
        isCustom: true,
      };
      setProfile(optimisticProfile);
      setCachedProfile(user.id, optimisticProfile);
    }

    if (!token) return true;

    try {
      const res = await fetch(getApiUrl("/api/profile"), {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ displayName: trimmed }),
      });

      if (res.ok) {
        const data = (await res.json()) as { profile: UserProfile };
        if (data.profile && user) {
          const savedProfile: UserProfile = {
            ...data.profile,
            isCustom: true,
          };
          setProfile(savedProfile);
          setCachedProfile(user.id, savedProfile);
        }
        return true;
      }
      return true; // Keep local profile even if backend sync temporarily fails
    } catch (err) {
      console.warn("Failed to sync display name to backend:", err);
      return true; // Keep local optimistic profile
    }
  }

  async function signOut() {
    if (user) {
      if (typeof window !== "undefined") {
        localStorage.removeItem(`${CUSTOM_NAME_KEY_PREFIX}${user.id}`);
      }
      clearCachedProfile(user.id);
    }
    await supabase.auth.signOut();
    setUser(null);
    setProfile(null);
    setToken(null);
    setLoading(false);
  }

  return {
    user,
    profile,
    token,
    loading,
    updateDisplayName,
    signOut,
  };
}
